### ISSUE TITLE
[src/05-led-roulette] microbit v2.2 "Error attaching to RTT"

### ISSUE THREAD

**Issue by mattjperez** [rust-embedded/discovery#472]
~~TLDR: microbit v2.2 runs then fails immediately when using RTT.~~
TLDR: I misconfigured the Embed.toml. `rtt-target` is stable even after running 5min.

Section 5.5 requires us to use the `rtt-target` crate however it appears the microbit v2.2 is having issues regarding RTT.
~~I believe this is related to https://github.com/probe-rs/probe-rs/issues/1235.~~

```
Finished flashing in 1.964s
    GDB stub listening at 127.0.0.1:1337
       Error Error attaching to RTT: RTT control block not found in target memory.
             - Make sure RTT is initialized on the target, AND that there are NO target breakpoints before RTT initalization.
             - For VSCode and probe-rs-debugger users, using `halt_after_reset:true` in your `launch.json` file will prevent RTT
                initialization from happening on time.
             - Depending on the target, sleep modes can interfere with RTT.
```

To confirm, I removed the call to `rprintln!()` and replaced `rtt_init_print` with `rtt_init_default`, and received the same results as above.
 
```toml
# Embed.toml
[default.general]
chip = "nrf52833_xxAA" # uncomment this line for micro:bit V2

[default.reset]
halt_afterwards = true

[default.rtt]
enabled = true

[default.gdb]
enabled = true
```
